name: Auto Assign to Project

on:
  issues:
    types: [opened]

env:
  MY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    permissions: write-all
    continue-on-error: true
    name: Assign to One Project
    steps:
    - name: Assign NEW issues and NEW pull requests to project 2
      uses: srggrs/assign-one-project-github-action@65a8ddab497df42ef268001e67bbf976f8fd39e1 # tag v1.3.1
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/users/hannahramadan/projects/1'
        column_name: 'Triage'
